compute_engine_instance:
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-14-3-release-amd64-ufs
  cpu: 4
  memory: 4G
  disk: 40

env:
  PKG_FORMAT: tar

task:
  matrix:
  - name: amd64-llvm19 build + smoke test
    env:
      TARGET: amd64
      TARGET_ARCH: amd64
      TOOLCHAIN: llvm19
      TOOLCHAIN_PKG: llvm19-lite

  - name: amd64-gcc14 build + smoke test
    env:
      TARGET: amd64
      TARGET_ARCH: amd64
      TOOLCHAIN: amd64-gcc14
      TOOLCHAIN_PKG: amd64-gcc14
      EXTRA_MAKE_FLAGS: -s

  timeout_in: 90m

  install_script:
    - sh .cirrus-ci/pkg-install.sh ${TOOLCHAIN_PKG} git-lite

  setup_script:
    - uname -a
    - df -m
    - pkg --version
    - pw useradd -n user -m
    - mkdir -p /usr/obj/$(pwd -P)
    - chown user:user /usr/obj/$(pwd -P)
    - su user -c "git config --global --add safe.directory $(pwd -P)"

  build_world_script:
    - su user -c "make -j$(sysctl -n hw.ncpu) ${EXTRA_MAKE_FLAGS} CROSS_TOOLCHAIN=${TOOLCHAIN} WITHOUT_TOOLCHAIN=yes buildworld"

  build_kernel_script:
    - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=${TOOLCHAIN} WITHOUT_TOOLCHAIN=yes buildkernel"

  test_script:
    - sh .cirrus-ci/pkg-install.sh qemu-nox11
    - sh tools/boot/ci-qemu-test.sh

  post_script:
    - df -m
    - du -m -s /usr/obj
